models/Employee.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "employee".
 *
 * @property int $id
 * @property string $first_name
 * @property string|null $middle_name
 * @property string $last_name
 * @property string|null $employee_code
 * @property int $mobile
 * @property int|null $alternate_mobile
 * @property string|null $email
 * @property int|null $gender
 * @property string|null $dob
 * @property int|null $state
 * @property int|null $district
 * @property string|null $city
 * @property string|null $address
 * @property int|null $pincode
 * @property string|null $profile_photo
 * @property int|null $company_id
 * @property int|null $user_id
 * @property int $aadhar_no
 * @property string|null $pan_no
 * @property string $created_at
 * @property int|null $created_by
 * @property string $updated_at
 * @property int|null $updated_by
 */
class Employee extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'employee';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'mobile', 'aadhar_no', 'state', 'district', 'city', 'address', 'pincode', 'gender'], 'required'],
            [['mobile', 'alternate_mobile', 'gender', 'state', 'pincode', 'company_id', 'user_id', 'aadhar_no', 'created_by', 'updated_by'], 'integer'],
            [['dob', 'created_at', 'updated_at'], 'safe'],
            [['address'], 'string'],
            [['first_name', 'middle_name', 'last_name', 'profile_photo'], 'string', 'max' => 30],
            [['employee_code', 'pan_no'], 'string', 'max' => 10],
            [['email', 'city'], 'string', 'max' => 50],
            [['email'], 'email'],
            [['first_name', 'last_name', 'middle_name', 'city'], 'match', 'pattern'=> '/[a-zA-Z ]+$/'],
            [['employee_code'], 'match', 'pattern'=> '/[a-zA-Z0-9-]+$/'],            
            [['mobile', 'alternate_mobile'], 'match', 'pattern' => '/^[6-9][0-9]{9}$/', 'message' => 'Invalid Mobile Number'],           
            [['pan_no'], 'match', 'pattern'=> '/^([A-Z]){5}([0-9]){4}([A-Z]){1}?$/'],
            [['aadhar_no'], 'match', 'pattern'=> '/[2-9]{1}[0-9]{11}$/'],
            [['pincode'], 'match', 'pattern'=> '/[0-9]+$/'],  
            [['pincode'], 'string', 'min'=> '6'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'First Name',
            'middle_name' => 'Middle Name',
            'last_name' => 'Last Name',
            'employee_code' => 'Employee Code',
            'mobile' => 'Mobile',
            'alternate_mobile' => 'Alternate Mobile',
            'email' => 'Email',
            'gender' => 'Gender',
            'dob' => 'Dob',
            'state' => 'State',
            'district' => 'District',
            'city' => 'City',
            'address' => 'Address',
            'pincode' => 'Pincode',
            'profile_photo' => 'Profile Photo',
            'company_id' => 'Company ID',
            'user_id' => 'User ID',
            'aadhar_no' => 'Aadhar No',
            'pan_no' => 'Pan No',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }
}

controllers/EmployeeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Employee;
use app\models\EmployeeSearch;
use app\models\MasterDistrict;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\widgets\ActiveForm;
use app\components\Encryption;
use app\models\EmployeeBankDetails;
use app\models\EmployeeOfficialDetails;
use app\models\EmployeePfDetails;

/**
 * EmployeeController implements the CRUD actions for Employee model.
 */
class EmployeeController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Employee models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EmployeeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);       
        $dataProvider->query->andWhere(['company_id' => Yii::$app->user->identity->company_id]);        
        $dataProvider->sort = ['defaultOrder' => ['first_name' => SORT_ASC]];
        $dataProvider->pagination->pageSize = Yii::$app->request->queryParams['per-page'] ?? 10;
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Employee model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Employee model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Employee();

        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }

            $model->dob = date('Y-m-d', strtotime($model->dob));            
            $model->company_id = Yii::$app->user->identity->company_id;
            $model->created_by = Yii::$app->user->identity->id;
            if ($model->save()) {                
                Yii::$app->session->setFlash("success", "Employee created successfully..!!");
                return $this->redirect(['index']);
            }
        }

        return $this->renderAjax('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Employee model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $id = Encryption::Decrypt($id);
        Yii::$app->session->set('empid', $id);
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            $model->dob = date('Y-m-d', strtotime($model->dob)); 
            $model->updated_by = Yii::$app->user->identity->id;
            if ($model->save()) {                
                Yii::$app->session->setFlash("success", "Employee Basic details Updated successfully..!!");
                //return $this->redirect(['index']);
            }
        }

        return $this->render('employee-details', [
            'data' => [
                'model' => $model,
            ]
        ]);
    }

    /**
     * Deletes an existing Employee model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Employee model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employee the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employee::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionGetDistrict(){
        $stateId = Yii::$app->request->post()['stateId'];
        $data = MasterDistrict::find()->where(['state_id' => $stateId])->all();
        $option = "<option value=''>Select District</option>";
        foreach($data as $val){
            $option .= "<option '".$val['id']."'>".$val['name']."</option>";
        }
        return $option;
    }
    public function actionBankDetails($id){
        $id = Encryption::Decrypt($id);
        $modelUpdate = EmployeeBankDetails::find()->where(['employee_id' => $id])->one();        
        $model = $modelUpdate ? $modelUpdate : new EmployeeBankDetails();
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } 
            $model->employee_id = $id;
            $model->created_by = Yii::$app->user->identity->id;
            if ($model->save()) {                
                Yii::$app->session->setFlash("success", "Bank Details updated successfully..!!");
                //return $this->redirect(['index']);
            }
        }
        return $this->render('employee-details', [
            'data' => [
                'model' => $model,
            ]
        ]);
    }

    public function actionOfficialDetails($id){
        $id = Encryption::Decrypt($id);
        $modelUpdate = EmployeeOfficialDetails::find()->where(['employee_id' => $id])->one();        
        $model = $modelUpdate ? $modelUpdate : new EmployeeOfficialDetails();
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } 
            $model->employee_id = $id;
            $model->doj = date('Y-m-d', strtotime($model->doj));
            $model->created_by = Yii::$app->user->identity->id;
            if ($model->save()) {                
                Yii::$app->session->setFlash("success", "Official Details updated successfully..!!");
                //return $this->redirect(['index']);
            }
        }
        return $this->render('employee-details', [
            'data' => [
                'model' => $model,
            ]
        ]);
    }

    public function actionOtherDetails($id){
        
        $id = Encryption::Decrypt($id);
        $modelUpdate = EmployeePfDetails::find()->where(['employee_id' => $id])->one();        
        $model = $modelUpdate ? $modelUpdate : new EmployeePfDetails();
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } 
            $model->employee_id = $id;
            $model->created_by = Yii::$app->user->identity->id;
            if ($model->save()) {                
                Yii::$app->session->setFlash("success", "Other Details updated successfully..!!");
               // return $this->redirect(['index']);
            }
        }
        return $this->render('employee-details', [
            'data' => [
                'model' => $model,
            ]
        ]);
    }
    
}

views/employee/_form.php
<?php

use app\models\MasterDistrict;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;
use kartik\select2\Select2;
use app\models\MasterState;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="card">
    <?php
    $form = ActiveForm::begin([
        'enableClientValidation' => false,
        'enableAjaxValidation' => true,
        'id' => 'form-add-user',
        'class' => 'form-horizontal',
        //'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-sm-3 col-form-label',
                'wrapper' => 'col-sm-6',
                'error' => '',
                'hint' => '',
            ],
        ],
    ]);
    ?>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'first_name')->textInput(['maxlength' => 20]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'middle_name')->textInput(['maxlength' => 20]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'last_name')->textInput(['maxlength' => 20]) ?>
            </div>            
            <div class="col-md-4">
            <?= $form->field($model, 'mobile')->textInput(['maxlength' => 10]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'alternate_mobile')->textInput(['maxlength' => 10]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'email')->textInput(['maxlength' => 50]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'employee_code')->textInput(['maxlength' => 10]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, "gender")->widget(Select2::className(), [
                        'data' => Yii::$app->params['gender'],
                        'options' => [ 'placeholder' => 'Select Gender'],            
                ]) ?>
            <?php // $form->field($model, 'gender')->inline()->radioList(Yii::$app->params['gender']); ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'dob')->widget(DatePicker::className(), [
                'options' => ['class' => 'calculate form-control'],
                'dateFormat' => 'dd-MM-yyyy',
                'clientOptions' => [
                    'maxDate' => date('d-m-Y', strtotime('-18 year')),
                    'changeMonth'=> true,
                    'changeYear'=> true,
                    'yearRange' => '1970:2030',
                ]
            ]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, "state")->widget(Select2::className(), [
                        'data' => ArrayHelper::map(MasterState::find()->all(), 'id', 'name'),
                        'options' => [ 'placeholder' => 'Select State'],            
                ]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, "district")->widget(Select2::className(), [
                        'data' => $model->isNewRecord ? [] : ArrayHelper::map(MasterDistrict::find()->where(['state_id' => $model->state])->all(), 'id', 'name'),
                        'options' => [ 'placeholder' => 'Select District'],            
                ]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'address')->textInput() ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'pincode')->textInput(['maxlength' => 6]) ?>
            </div>
            <!-- <div class="col-md-4">
            <?php // $form->field($model, 'profile_photo')->textInput(['maxlength' => true]) ?>
            </div>             -->
            <div class="col-md-4">
            <?= $form->field($model, 'aadhar_no')->textInput(['maxlength' => 12]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'pan_no')->textInput(['maxlength' => 10, 'class' => 'form-control input-uppercase']) ?>
            </div>
          
        </div>
    </div>
    <div class="card-footer">
        <?= Html::submitButton($model->isNewRecord ? 'Save' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a('Cancel', ['index'], ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

<?php
$getDistrict = Url::to(['employee/get-district']);

$script = <<< JS
    
    $('.input-uppercase').keyup(function () {        
        this.value = this.value.toUpperCase();
    });

    $('#employee-state').change(function(){
       var stateId = $(this).val();
       $.post('$getDistrict', {stateId:stateId}, function(data){
            $('#employee-district').html(data);
       });
    });
JS;
$this->registerJs($script);
?>

views/employee/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EmployeeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employee-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'middle_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'employee_code') ?>

    <?php // echo $form->field($model, 'mobile') ?>

    <?php // echo $form->field($model, 'alternate_mobile') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'gender') ?>

    <?php // echo $form->field($model, 'dob') ?>

    <?php // echo $form->field($model, 'state') ?>

    <?php // echo $form->field($model, 'district') ?>

    <?php // echo $form->field($model, 'city') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'pincode') ?>

    <?php // echo $form->field($model, 'profile_photo') ?>

    <?php // echo $form->field($model, 'company_id') ?>

    <?php // echo $form->field($model, 'aadhar_no') ?>

    <?php // echo $form->field($model, 'pan_no') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/employee/bank-details.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EmployeeBankDetails */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="card">

    <?php
    $form = ActiveForm::begin([
        'enableClientValidation' => false,
        'enableAjaxValidation' => true,
        'id' => 'form-add-user',
        'class' => 'form-horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
        ],
    ]);
    ?>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'account_number')->textInput(['maxlength' => 16]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'bank_name')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'ifsc_code')->textInput(['maxlength' => 11, 'class' => 'form-control input-uppercase']) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'bank_code')->textInput(['maxlength' => true, 'class' => 'form-control input-uppercase']) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'bank_address')->textInput(['maxlength' => true]) ?>
            </div>
        </div>
    </div>

    <div class="card-footer">
        <?= Html::submitButton('Update', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Cancel', ['index'], ['class' => 'btn btn-default']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>
<?php
$script = <<< JS
    
    $('.input-uppercase').keyup(function () {        
        this.value = this.value.toUpperCase();
    });
JS;
$this->registerJs($script);
?>

views/employee/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */

$this->title = 'Create Employee';
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employee-create">   

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/employee/employee-details.php
<?php

use yii\helpers\Url;
use app\components\Encryption;

/* @var $this yii\web\View */
/* @var $model app\models\User */
extract($data);
$this->title = 'Update Employee Details';
$action = Yii::$app->controller->action->id;
$empid = Yii::$app->session->get('empid');
?>
<div class="user-update">
    <div class="row">
        <!-- /.col -->
        <div class="col-md-12">
            <div class="card card-primary card-outline card-outline-tabs">
                <div class="card-header p-0 border-bottom-0">
                    <ul class="nav nav-tabs">
                        <li class="nav-item"><a class="nav-link <?= $action == 'update' ? 'active' : '' ?>"  href="<?= Url::to(['update', 'id' => Encryption::Encrypt($empid)]) ?>">Basic Details</a></li></li>
                        <li class="nav-item"><a class="nav-link <?= $action == 'official-details' ? 'active' : '' ?>"  href="<?= Url::to(['official-details', 'id' => Encryption::Encrypt($empid)]) ?>">Official Details</a></li>
                        <li class="nav-item"><a class="nav-link <?= $action == 'bank-details' ? 'active' : '' ?>"  href="<?= Url::to(['bank-details', 'id' => Encryption::Encrypt($empid)]) ?>">Bank Details </a></li>                        
                        <li class="nav-item"><a class="nav-link <?= $action == 'other-details' ? 'active' : '' ?>"  href="<?= Url::to(['other-details', 'id' => Encryption::Encrypt($empid)]) ?>">Other Details</a></li>                        
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content py-3 ">
                        <?= $this->render("$action", $data) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/employee/index.php
<?php

use yii\helpers\Html;
use app\components\GridView;
use app\components\Encryption;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EmployeeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Employees';
$this->params['breadcrumbs'][] = $this->title;
?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,        
        'exportTitle' => $this->title,
        'panel' => ['type' => GridView::TYPE_SECONDARY, 'heading' => $this->title],
        'export' => ['showConfirmAlert' => false,],
        'pjax' => true,
        'toolbar' => [
            Html::a('<i class="fa fa-plus"></i> Add New', ['create'], ['class' => 'btn btn-sm btn-success employee float-right', 'title' => 'Add Employee',  'data-pjax' => 0]),
            '{export}',
            '{perPage}',
        ],
        'options' => [
            'class' => 'grid-primary',
        ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'first_name',
                'label' => 'EMP Name',
                'value' => function($model){
                    return $model->first_name." ".$model->middle_name." ".$model->last_name;
                }
            ],            
            'employee_code',
            'mobile',            
            'email',
            //'gender',
            [
                'label' => 'DOB',
                'contentOptions' => ['width' => 100],
                 'value' => function($model){
                    return date('d-m-Y', strtotime($model->dob));
                 }
            ],            
            //'state',
            //'district',
            //'city',
            //'address:ntext',
            //'pincode',
            //'profile_photo',
            //'company_id',            
            'aadhar_no',
            'pan_no',
            //'created_at',
            //'created_by',
            //'updated_at',
            //'updated_by',

            [
                'header' => "Action",
                'headerOptions' => ['class' => "skip-export text-center", 'width' => 150],
                'format' => 'raw',
                'contentOptions' => ['class' => "skip-export text-center", 'width' => 150],
                'value' => function($model) {
                    $list = [];   
                    $list[] = Html::a('<i class="fa fa-pencil-alt" title="Update"></i> ', ['update', "id" => Encryption::Encrypt($model->id)], ['class' => 'btn btn-xs btn-info', 'title' => 'Update Employee', 'data-pjax' => 0]);
                    return implode('', $list);
                },
            ],
        ],
    ]); ?>

</div>
<?php
$script = <<< JS
    $("body").on('click', '.employee',function(e) {
        e.preventDefault();
        $("#employeeModalContent").load($(this).attr('href'));
        $("#employeeModalTitle").text($(this).attr('title'));
        $('#employeeModal').modal('show');
    });        
    
JS;
$this->registerJs($script);
echo $this->render("@app/views/layouts/models/_ajaxRenderModal", [
    'headerTitleId' => 'employeeModalTitle',
    'modalId' => "employeeModal",
    'contentId' => "employeeModalContent",
    'size' => 'xl'
]);

?>

views/employee/official-details.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use app\models\MasterDepartment;
use app\models\MasterDesignation;
use app\models\MasterShift;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;
use kartik\select2\Select2;
/* @var $this yii\web\View */
/* @var $model app\models\EmployeeOfficialDetails */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="card">

    <?php
    $form = ActiveForm::begin([
        'enableClientValidation' => false,
        'enableAjaxValidation' => true,
        'id' => 'form-add-user',
        'class' => 'form-horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}"
        ],
    ]);
    ?>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
            <?= $form->field($model, "department_id")->widget(Select2::className(), [
                        'data' => ArrayHelper::map(MasterDepartment::find()->where(['company_id' => Yii::$app->user->identity->company_id])->all(), 'id', 'name'),
                        'options' => [ 'placeholder' => 'Select Department'],            
                ]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, "designation_id")->widget(Select2::className(), [
                        'data' => ArrayHelper::map(MasterDesignation::find()->where(['company_id' => Yii::$app->user->identity->company_id])->all(), 'id', 'name'),
                        'options' => [ 'placeholder' => 'Select Designation'],            
                ]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'basic_salary')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'doj')->widget(DatePicker::className(), [
                'options' => ['class' => 'form-control', 'changeYear'=> true,],
                'dateFormat' => 'dd-MM-yyyy',
                'clientOptions' => [
                    'maxDate' => date('d-m-Y'),
                    'changeMonth'=> true,
                    'changeYear'=> true,
                    'yearRange' => '1970:2030',
                ]              
            ]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'security_deposit')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, "shift")->widget(Select2::className(), [
                        'data' => ArrayHelper::map(MasterShift::find()->where(['company_id' => Yii::$app->user->identity->company_id])->all(), 'company_shift_id', 'shift_name'),
                        'options' => [ 'placeholder' => 'Select Department'],            
                ]) ?>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <?= Html::submitButton('Update', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Cancel', ['index'], ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/employee/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */

$this->title = 'Update Employee: ' . $model->first_name;
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->first_name];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="employee-update">   

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>